style_edition = "2024"
edition = "2024"
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
