# Based on typst's release action:
# https://github.com/typst/typst/blob/main/.github/workflows/release.yml

name: Test
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/**"
    tags-ignore:
      - "**"
  workflow_dispatch:

jobs:
  format:
    name: Code Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check

  check:
    name: Clippy Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all --workspace --all-targets -- -Dwarnings

  unit-test:
    name: Unit Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Run Unit Tests
        run: cargo test --workspace --all-targets -- --test-threads=1

  test-build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            feature: vendored
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
            feature: vendored
          - target: aarch64-apple-darwin
            os: macos-latest
            feature: default
          - target: x86_64-apple-darwin
            os: macos-13
            feature: default
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            feature: default
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
            feature: default

    steps:
      - uses: actions/checkout@v4

      - name: Install Cross-Compilation Tools
        if: contains(matrix.target, 'linux-musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config libssl-dev
          # echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Run Build
        run: cargo build --verbose --release --target ${{ matrix.target }} -F ${{ matrix.feature }}

      # We might include unit test in the future, but we don't have any at the time
