# Based on typst's release action:
# https://github.com/typst/typst/blob/main/.github/workflows/release.yml

name: Test Build Binaries
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/**"
    tags-ignore:
      - "**"
  workflow_dispatch:

jobs:
  test-build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - target: armv7-unknown-linux-musleabi
            os: ubuntu-latest
            cross: true
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
          - target: aarch64-apple-darwin
            os: macos-latest
            cross: false
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Run Cross
        if: ${{ matrix.cross }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git
          cross build --release --target ${{ matrix.target }}

      - name: Run Cargo
        if: ${{ !matrix.cross }}
        run: cargo build --release --target ${{ matrix.target }}

      # We might include unit test in the future, but we don't have any at the time
